% j_3DOF_PSD    Compute PSD on data from a simulation of a 3DOF system. The
%               3DOF data must have been generated by running example
%               i_3DOF_MKz in folder 'chapter6'. Two blocksizes are
%               compared, and the true PSD is overlaid with the estimated
%               in both cases.
%

% This example is similar to the plot in Fig. 10.17 in Brandt.

% This file is part of the examples for the ABRAVIBE Toolbox for NVA which 
% is an accompanying toolbox for the book
% Brandt, Anders: "Noise and Vibration Analysis: Signal Analysis and
% Experimental Procedures," Wiley 2011. ISBN: 13-978-0-470-74644-8.
% Copyright 2011, Anders Brandt.

clear
clc
close all

% Some settings to easily change plot appearance
%--------------------------------------------------
FontSize=9;
FontName='Times New Roman';
LineWidth=1;
LineType={'-k','--k','-.k',':k'};

%--------------------------------------------------
% PSD of 3DOF system
FileName='..\data\3dofmkz.mat';

if exist(FileName,'file') ~= 2
    fprintf('You first must run example i_3DOF_MKz in folder ''chapter6''\n')
else
    load(FileName)
    % First compute a PSD with coarse PSD causing a high bias error
    subplot(2,2,1)
    [Gyy,fy]=apsdw(y,fs,N/2);
    semilogy(fy,Gyy,LineType{1},f,Gyyt,LineType{4},'LineWidth',LineWidth)
    xlabel('Frequency [Hz]','FontName',FontName,'FontSize',FontSize)
    ylabel('Acceleration PSD [(m/s^2)^2/Hz]','FontName',FontName,'FontSize',FontSize)
    grid
    axis([0 400 1e-5 200])
    set(gca,'YTick',[1e-4 1e-2 1 1e2])
    title('Blocksize N=1024','FontName',FontName,'FontSize',FontSize)
    set(gca,'FontName',FontName,'FontSize',FontSize)
    % Zoom in and plot again, around first resonance (which has the
    % narrowest resonance peak since the damping is constant for all modes)
    subplot(2,2,2)
    semilogy(fy,Gyy,LineType{1},f,Gyyt,LineType{4},'LineWidth',LineWidth)
    xlabel('Frequency [Hz]','FontName',FontName,'FontSize',FontSize)
    ylabel('Acceleration PSD [(m/s^2)^2/Hz]','FontName',FontName,'FontSize',FontSize)
    % grid
    axis([96 101 .6 6])
    set(gca,'YTick',[1 5])
    title('Blocksize N=1024','FontName',FontName,'FontSize',FontSize)
    set(gca,'FontName',FontName,'FontSize',FontSize)
    % Now do the same again, using a higher blocksize, thus a finer
    % frequency increment
    subplot(2,2,3)
    [Gyy,fy]=apsdw(y,fs,2*N);
    semilogy(fy,Gyy,LineType{1},f,Gyyt,LineType{4},'LineWidth',LineWidth)
    xlabel('Frequency [Hz]','FontName',FontName,'FontSize',FontSize)
    ylabel('Acceleration PSD [(m/s^2)^2/Hz]','FontName',FontName,'FontSize',FontSize)
    grid
    axis([0 400 1e-5 200])
    set(gca,'YTick',[1e-4 1e-2 1 1e2])
    title('Blocksize N=4096','FontName',FontName,'FontSize',FontSize)
    set(gca,'FontName',FontName,'FontSize',FontSize)
    % And zoom in and plot again
    subplot(2,2,4)
    semilogy(fy,Gyy,LineType{1},f,Gyyt,LineType{4},'LineWidth',LineWidth)
    xlabel('Frequency [Hz]','FontName',FontName,'FontSize',FontSize)
    ylabel('Acceleration PSD [(m/s^2)^2/Hz]','FontName',FontName,'FontSize',FontSize)
    axis([96 101 .6 6])
    set(gca,'YTick',[1 5])
    title('Blocksize N=4096','FontName',FontName,'FontSize',FontSize)
    set(gca,'FontName',FontName,'FontSize',FontSize)
end